apps/funcionarios/urls.py
from django.urls import path
from apps.funcionarios.views import (
    FuncionarioCreate,
    FuncionarioList,
    FuncionarioEdit,
    FuncionarioDelete
)


urlpatterns = [
    path('', FuncionarioList.as_view(), name="list_funcionario"),
    path('novo/', FuncionarioCreate.as_view(), name="create_funcionario"),
    path(
        'editar/<int:pk>',
        FuncionarioEdit.as_view(),
        name="update_funcionario"
    ),
    path(
        'deletar/<int:pk>',
        FuncionarioDelete.as_view(),
        name="delete_funcionario"
    ),
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# gambiarra to serve static files on development
from django.conf.urls.static import static

urlpatterns = [
    path("", include("apps.core.urls")),
    path("funcionarios/", include("apps.funcionarios.urls")),
    path("departamentos/", include("apps.departamentos.urls")),
    path("empresas/", include("apps.empresas.urls")),
    path('documentos/', include('apps.documentos.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # part of gambiarra too
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from django.shortcuts import reverse
from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(
        Funcionario, on_delete=models.PROTECT
    )
    arquivo = models.FileField(upload_to="documents")

    def get_absolute_url(self):
        return reverse("update_funcionario", args=[self.pertence.pk])

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa


class Funcionario(models.Model):
    nome = models.CharField(max_length=120)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(
            Empresa,
            on_delete=models.PROTECT,
            blank=True,
            null=True
        )

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('list_funcionario')

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView
)

from apps.funcionarios.models import Funcionario


class FuncionarioCreate(CreateView):
    model = Funcionario
    fields = ["nome", "departamentos"]
    success_url = reverse_lazy("list_funcionario")

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        if len(funcionario.nome.split(" ")) > 1:
            username = (
                funcionario.nome.split(" ")[0]+"."+funcionario.nome.split(" ")[1]
            ).lower()
        else:
            username = (
                funcionario.nome.split(" ")[0].lower()
            )
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(
            username=username
        )
        funcionario.save()
        return super(FuncionarioCreate, self).form_valid(form)


class FuncionarioList(ListView):
    model = Funcionario

    # listar apenas funcionários da empresa do usuário logado
    def get_queryset(self):
        empresa = self.request.user.funcionario.empresa
        queryset = Funcionario.objects.filter(empresa=empresa)
        return queryset


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ["nome", "departamentos"]
    success_url = reverse_lazy("list_funcionario")


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy("list_funcionario")

templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
<form action="" method="post">
    {% csrf_token %}
    <h1>Você está certo da remoção?</h1>
    {{ form }}
    <button type="submit" class="btn btn-danger">Confirmar</button>
</form>
{% endblock %}

templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
Funcionario:</br>
<form action="" method="post">
  {% csrf_token %}
  {{ form|bootstrap }}
  <button type="submit" class="btn btn-primary">Salvar</button>
</form>
{% if object %}
	<a href="{% url 'create_documento' object.pk %}" class="btn btn-success">Adicionar documento</a>
	{% for documento in funcionario.documento_set.all %}
		<br/><a href="{{ documento.arquivo.url }}">{{ documento.descricao }}</a>
	{% endfor %}
{% endif %}
{% endblock %}

templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
Lista de funcionários</br>
{% for funcionario in object_list %}
    <a href="{% url 'update_funcionario' funcionario.pk %}">{{ funcionario }}</a>
    <a href="{% url 'delete_funcionario' funcionario.pk %}">Deletar</a></br>
{% endfor %}
<a href="{% url 'create_funcionario' %}" class="btn btn-info">Novo</a>
{% endblock %}